In [1]:
import xarray as xr

ds_instant = xr.open_dataset('./a410b01a0b3d4ee1b01b661ca754a713/data_stream-oper_stepType-instant.nc')
ds_accum = xr.open_dataset("./a410b01a0b3d4ee1b01b661ca754a713/data_stream-oper_stepType-accum.nc")

In [1]:
from pathlib import Path
import xarray as xr
import pandas as pd
base_dir = Path(".")  

all_nc = list(base_dir.rglob("*.nc"))

rows = []

for file in all_nc:
    ds = xr.open_dataset(file)

    time_name = "valid_time" if "valid_time" in ds.coords else "time"
    times = pd.to_datetime(ds[time_name].values)

    rows.append({
        "file": str(file),
        "type": "accum" if "accum" in file.name else "instant" if "instant" in file.name else "other",
        "start": times.min(),
        "end": times.max(),
        "years": sorted(set(times.year)),
        "months": sorted(set(times.month)),
        "n_times": len(times)
    })

files_info = pd.DataFrame(rows)
files_info

,file,type,start,end,years,months,n_times
0,1a74942c3f0dc3b851ebb49f704c1ab4/data_stream-o...,accum,2024-05-01,2024-09-30 23:00:00,[2024],"[5, 6, 7, 8, 9]",3672
1,1a74942c3f0dc3b851ebb49f704c1ab4/data_stream-o...,instant,2024-05-01,2024-09-30 23:00:00,[2024],"[5, 6, 7, 8, 9]",3672
2,714a357dc7a31f2b65486abcd83b3c47/data_stream-o...,accum,2022-05-01,2022-09-30 23:00:00,[2022],"[5, 6, 7, 8, 9]",3672
3,714a357dc7a31f2b65486abcd83b3c47/data_stream-o...,instant,2022-05-01,2022-09-30 23:00:00,[2022],"[5, 6, 7, 8, 9]",3672
4,831893f88cc0000e23748e601b66b60a/data_stream-o...,accum,2023-05-01,2023-09-30 23:00:00,[2023],"[5, 6, 7, 8, 9]",3672
5,831893f88cc0000e23748e601b66b60a/data_stream-o...,instant,2023-05-01,2023-09-30 23:00:00,[2023],"[5, 6, 7, 8, 9]",3672
6,3dd81707afb59795bc103f9cb7b7cb61/data_stream-o...,accum,2025-05-01,2025-09-30 23:00:00,[2025],"[5, 6, 7, 8, 9]",3672
7,3dd81707afb59795bc103f9cb7b7cb61/data_stream-o...,instant,2025-05-01,2025-09-30 23:00:00,[2025],"[5, 6, 7, 8, 9]",3672
8,a410b01a0b3d4ee1b01b661ca754a713/data_stream-o...,accum,2019-05-01,2019-09-30 23:00:00,[2019],"[5, 6, 7, 8, 9]",3672
9,a410b01a0b3d4ee1b01b661ca754a713/data_stream-o...,instant,2019-05-01,2019-09-30 23:00:00,[2019],"[5, 6, 7, 8, 9]",3672
10,391f004915db8ebcb01569bfd11b7247/data_stream-o...,accum,2020-05-01,2020-09-30 23:00:00,[2020],"[5, 6, 7, 8, 9]",3672
11,391f004915db8ebcb01569bfd11b7247/data_stream-o...,instant,2020-05-01,2020-09-30 23:00:00,[2020],"[5, 6, 7, 8, 9]",3672
12,4eb9508671f184b580910da9b60a2189/data_stream-o...,accum,2021-05-01,2021-09-30 23:00:00,[2021],"[5, 6, 7, 8, 9]",3672
13,4eb9508671f184b580910da9b60a2189/data_stream-o...,instant,2021-05-01,2021-09-30 23:00:00,[2021],"[5, 6, 7, 8, 9]",3672

In [15]:
files_info.sort_values(["type", "start", "end"])

,file,type,start,end,years,months,n_times
8,a410b01a0b3d4ee1b01b661ca754a713/data_stream-o...,accum,2019-05-01,2019-09-30 23:00:00,[2019],"[5, 6, 7, 8, 9]",3672
10,391f004915db8ebcb01569bfd11b7247/data_stream-o...,accum,2020-05-01,2020-09-30 23:00:00,[2020],"[5, 6, 7, 8, 9]",3672
12,4eb9508671f184b580910da9b60a2189/data_stream-o...,accum,2021-05-01,2021-09-30 23:00:00,[2021],"[5, 6, 7, 8, 9]",3672
2,714a357dc7a31f2b65486abcd83b3c47/data_stream-o...,accum,2022-05-01,2022-09-30 23:00:00,[2022],"[5, 6, 7, 8, 9]",3672
4,831893f88cc0000e23748e601b66b60a/data_stream-o...,accum,2023-05-01,2023-09-30 23:00:00,[2023],"[5, 6, 7, 8, 9]",3672
0,1a74942c3f0dc3b851ebb49f704c1ab4/data_stream-o...,accum,2024-05-01,2024-09-30 23:00:00,[2024],"[5, 6, 7, 8, 9]",3672
6,3dd81707afb59795bc103f9cb7b7cb61/data_stream-o...,accum,2025-05-01,2025-09-30 23:00:00,[2025],"[5, 6, 7, 8, 9]",3672
9,a410b01a0b3d4ee1b01b661ca754a713/data_stream-o...,instant,2019-05-01,2019-09-30 23:00:00,[2019],"[5, 6, 7, 8, 9]",3672
11,391f004915db8ebcb01569bfd11b7247/data_stream-o...,instant,2020-05-01,2020-09-30 23:00:00,[2020],"[5, 6, 7, 8, 9]",3672
13,4eb9508671f184b580910da9b60a2189/data_stream-o...,instant,2021-05-01,2021-09-30 23:00:00,[2021],"[5, 6, 7, 8, 9]",3672
3,714a357dc7a31f2b65486abcd83b3c47/data_stream-o...,instant,2022-05-01,2022-09-30 23:00:00,[2022],"[5, 6, 7, 8, 9]",3672
5,831893f88cc0000e23748e601b66b60a/data_stream-o...,instant,2023-05-01,2023-09-30 23:00:00,[2023],"[5, 6, 7, 8, 9]",3672
1,1a74942c3f0dc3b851ebb49f704c1ab4/data_stream-o...,instant,2024-05-01,2024-09-30 23:00:00,[2024],"[5, 6, 7, 8, 9]",3672
7,3dd81707afb59795bc103f9cb7b7cb61/data_stream-o...,instant,2025-05-01,2025-09-30 23:00:00,[2025],"[5, 6, 7, 8, 9]",3672

In [2]:
instant_files = [str(f) for f in all_nc if "instant" in f.name]
accum_files = [str(f) for f in all_nc if "accum" in f.name]

print("instant:", len(instant_files))
print("accum:", len(accum_files))

instant: 7
accum: 7

In [2]:
print(ds_instant)
print(ds_accum)

<xarray.Dataset> Size: 206kB
Dimensions:     (valid_time: 3672, latitude: 1, longitude: 2)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 29kB 2019-05-01 ... 2019-09-30T23...
    expver      (valid_time) <U4 59kB ...
  * latitude    (latitude) float64 8B 49.5
  * longitude   (longitude) float64 16B 20.75 21.0
    number      int64 8B ...
Data variables:
    u10         (valid_time, latitude, longitude) float32 29kB ...
    v10         (valid_time, latitude, longitude) float32 29kB ...
    t2m         (valid_time, latitude, longitude) float32 29kB ...
    sp          (valid_time, latitude, longitude) float32 29kB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-04-27T19:20 GRIB to CDM+CF via cfgrib-0.9.1...
<xarray.Dataset> Size: 118kB
Dimensions:     (valid_time: 3672, latitude: 1, longitude: 2)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 29kB 2019-05-01 ... 2019-09-30T23...
    expver      (valid_time) <U4 59kB ...
  * latitude    (latitude) float64 8B 49.5
  * longitude   (longitude) float64 16B 20.75 21.0
    number      int64 8B ...
Data variables:
    tp          (valid_time, latitude, longitude) float32 29kB ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-04-27T19:20 GRIB to CDM+CF via cfgrib-0.9.1...

In [3]:
lat = 49.39
lon = 20.87

inst = ds_instant.sel(latitude=lat, longitude=lon, method="nearest")
acc = ds_accum.sel(latitude=lat, longitude=lon, method="nearest")

In [4]:
df_inst = inst.to_dataframe().reset_index()
df_acc = acc.to_dataframe().reset_index()

In [6]:
print(df_inst.columns)
print(df_acc.columns)

Index(['valid_time', 'u10', 'v10', 't2m', 'sp', 'number', 'latitude',
       'longitude', 'expver'],
      dtype='str')
Index(['valid_time', 'tp', 'number', 'latitude', 'longitude', 'expver'], dtype='str')

In [7]:
df = df_inst.merge(df_acc, on="valid_time")

In [8]:
import numpy as np

df["temp"] = df["t2m"] - 273.15
df["wspd"] = np.sqrt(df["u10"]**2 + df["v10"]**2)
df["prcp"] = df["tp"] * 1000
df["pres"] = df["sp"] / 100  # Pa -> hPa

In [9]:
time_col = "time" if "time" in df.columns else "valid_time"

df_final = df[[time_col, "temp", "wspd", "prcp", "pres"]]
df_final.head()

           valid_time      temp      wspd      prcp        pres
0 2019-05-01 00:00:00  8.404327  3.310282  0.178814  941.632812
1 2019-05-01 01:00:00  8.166046  3.494877  0.156403  941.330444
2 2019-05-01 02:00:00  7.969513  3.636947  0.191212  941.262207
3 2019-05-01 03:00:00  7.678314  3.815005  0.128269  940.879395
4 2019-05-01 04:00:00  7.543060  3.679924  0.025272  940.967163

In [10]:
df_final.tail()

              valid_time       temp      wspd  prcp        pres
3667 2019-09-30 19:00:00  12.414276  6.615520   0.0  941.888428
3668 2019-09-30 20:00:00  12.084381  6.346275   0.0  942.625793
3669 2019-09-30 21:00:00  12.124084  6.048124   0.0  943.498779
3670 2019-09-30 22:00:00  12.026642  4.797307   0.0  944.148621
3671 2019-09-30 23:00:00  11.528534  4.471599   0.0  944.879517

In [2]:
from pathlib import Path
import xarray as xr

base_dir = Path(".")
all_nc = sorted(base_dir.rglob("*.nc"))

instant_files = [str(f) for f in all_nc if "instant" in f.name]
accum_files = [str(f) for f in all_nc if "accum" in f.name]

print("instant:", len(instant_files))
print("accum:", len(accum_files))
print(instant_files[:3])
print(accum_files[:3])

instant: 7
accum: 7
['1a74942c3f0dc3b851ebb49f704c1ab4/data_stream-oper_stepType-instant.nc', '391f004915db8ebcb01569bfd11b7247/data_stream-oper_stepType-instant.nc', '3dd81707afb59795bc103f9cb7b7cb61/data_stream-oper_stepType-instant.nc']
['1a74942c3f0dc3b851ebb49f704c1ab4/data_stream-oper_stepType-accum.nc', '391f004915db8ebcb01569bfd11b7247/data_stream-oper_stepType-accum.nc', '3dd81707afb59795bc103f9cb7b7cb61/data_stream-oper_stepType-accum.nc']

In [3]:
ds_inst = xr.open_mfdataset(instant_files, combine="by_coords")
ds_acc = xr.open_mfdataset(accum_files, combine="by_coords")

In [4]:
df_inst = ds_inst.to_dataframe().reset_index()
df_acc = ds_acc.to_dataframe().reset_index()

df = df_inst.merge(
    df_acc,
    on=["valid_time", "latitude", "longitude"]
)

In [6]:
import numpy as np
df["temp"] = df["t2m"] - 273.15
df["wspd"] = np.sqrt(df["u10"]**2 + df["v10"]**2)
df["pres"] = df["sp"] / 100
df["prcp"] = df["tp"] * 1000

In [8]:
df_weather = df[["valid_time", "latitude", "longitude", "temp", "wspd", "prcp", "pres"]]

df_weather.head()
df["prcp_hourly"] = df.groupby(["latitude", "longitude"])["tp"].diff() * 1000

In [9]:
df.tail()

,valid_time,latitude,longitude,u10,v10,t2m,sp,number_x,expver_x,tp,number_y,expver_y,temp,wspd,pres,prcp,prcp_hourly
51403,2025-09-30 21:00:00,49.5,21.00,-0.897293,-2.445694,279.779388,96549.562500,0,0001,0.000178,0,0001,6.629395,2.605102,965.495605,0.177860,0.062466
51404,2025-09-30 22:00:00,49.5,20.75,-0.486664,-2.207901,279.213501,95722.203125,0,0001,0.000209,0,0001,6.063507,2.260900,957.222046,0.208855,0.005245
51405,2025-09-30 22:00:00,49.5,21.00,-0.710297,-2.467667,279.574829,96527.203125,0,0001,0.000166,0,0001,6.424835,2.567859,965.272034,0.165939,-0.011921
51406,2025-09-30 23:00:00,49.5,20.75,-0.583267,-2.516617,279.101868,95703.265625,0,0001,0.000269,0,0001,5.951874,2.583323,957.032654,0.268936,0.060081
51407,2025-09-30 23:00:00,49.5,21.00,-0.908463,-2.787125,279.451477,96510.265625,0,0001,0.000223,0,0001,6.301483,2.931445,965.102661,0.222683,0.056744